name: docker image ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: build the docker image
        run: docker build . --file Dockerfile --tag spring-webflux-example:$(date+%s)